spring:
  application:
    name: enerflow-app
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

# Heat pump connection settings
heatpump:
  host: 192.168.178.138
  port: 8214
  password: ${HEATPUMP_PASSWORD}
  reconnect-delay-seconds: 30

logging:
  level:
    de.saki.enerflow: DEBUG
    org.java_websocket: DEBUG